#                                                           Assignment 3


###                                                                 Operations on Fuzzy Set and Relations

In [27]:

# Union of Two Fuzzy Sets
A = dict()
B = dict()
Y = dict()

A = {"a": 0.5, "b": 0.4, "c": 0.7, "d": 0.3,"e":0.8,"f":0.9}
B = {"a": 0.6, "b": 0.7, "c": 0.4, "d": 0.2,"e":0.8,"f":1}

print('The First Fuzzy Set is :', A)
print('The Second Fuzzy Set is :', B)


for A_key, B_key in zip(A, B):
	A_value = A[A_key]
	B_value = B[B_key]

	if A_value > B_value:
		Y[A_key] = A_value
	else:
		Y[B_key] = B_value
		
print('Fuzzy Set Union is\t:', Y)


The First Fuzzy Set is : {'a': 0.5, 'b': 0.4, 'c': 0.7, 'd': 0.3, 'e': 0.8, 'f': 0.9}
The Second Fuzzy Set is : {'a': 0.6, 'b': 0.7, 'c': 0.4, 'd': 0.2, 'e': 0.8, 'f': 1}
Fuzzy Set Union is	: {'a': 0.6, 'b': 0.7, 'c': 0.7, 'd': 0.3, 'e': 0.8, 'f': 1}


In [26]:
# Example to Demonstrate
# Intersection of Two Fuzzy Sets
A = dict()
B = dict()
Y = dict()

A = {"a": 0.3, "b": 0.5, "c": 0.7, "d": 0.6, "e":0.7, "f":0.8}
B = {"a": 0.4, "b": 0.6, "c": 0.7, "d": 0.8, "e":0.9, "f":1}

print('The First Fuzzy Set is :', A)
print('The Second Fuzzy Set is :', B)


for A_key, B_key in zip(A, B):
	A_value = A[A_key]
	B_value = B[B_key]

	if A_value < B_value:
		Y[A_key] = A_value
	else:
		Y[B_key] = B_value
print('Fuzzy Set Intersection is :', Y)


The First Fuzzy Set is : {'a': 0.3, 'b': 0.5, 'c': 0.7, 'd': 0.6, 'e': 0.7, 'f': 0.8}
The Second Fuzzy Set is : {'a': 0.4, 'b': 0.6, 'c': 0.7, 'd': 0.8, 'e': 0.9, 'f': 1}
Fuzzy Set Intersection is : {'a': 0.3, 'b': 0.5, 'c': 0.7, 'd': 0.6, 'e': 0.7, 'f': 0.8}


In [33]:

# Difference Between Two Fuzzy Sets
A = dict()
B = dict()
Y = dict()

A = {"a": 0.3, "b": 0.5, "c": 0.7, "d": 0.6, "e":0.7, "f":0.8}
B = {"a": 0.4, "b": 0.6, "c": 0.7, "d": 0.8, "e":0.9, "f":1}

print('The First Fuzzy Set is :', A)
print('The Second Fuzzy Set is :', B)


for A_key, B_key in zip(A, B):
	A_value = A[A_key]
	B_value = B[B_key]
	B_value = 1 - B_value

	if A_value < B_value:
		Y[A_key] = A_value
	else:
		Y[B_key] = B_value
		
print('\nFuzzy Set Difference is :', Y)


The First Fuzzy Set is : {'a': 0.3, 'b': 0.5, 'c': 0.7, 'd': 0.6, 'e': 0.7, 'f': 0.8}
The Second Fuzzy Set is : {'a': 0.4, 'b': 0.6, 'c': 0.7, 'd': 0.8, 'e': 0.9, 'f': 1}

Fuzzy Set Difference is : {'a': 0.3, 'b': 0.4, 'c': 0.30000000000000004, 'd': 0.19999999999999996, 'e': 0.09999999999999998, 'f': 0}


In [43]:

import numpy as np
def maxMin(a,b):
    z=[]
    for x1 in a:
        for y1 in b:
            z.append(max(np.minimum(x1, y1)))
    return np.array(z).reshape((a.shape[0], b.shape[0]))
def maxProduct(a,b):
    z=[]
    for x1 in a:
        for y1 in b:
            z.append(max(np.multiply(x1, y1)))
    return np.array(z).reshape((a.shape[0], b.shape[0]))
a=np.array([[0.3,0.5,0.7],[0.6,0.7,0.8]])
b=np.array([[0.4,0.6,0.7],[0.8,0.9,1]])
print('a=>\n',a)
print('b=>\n',b)
print('Max-Min=>\n',str(maxMin(a,b)))
print("Max-Product => :\n" + str(maxProduct(a, b)) + "\n\n")

a=>
 [[0.3 0.5 0.7]
 [0.6 0.7 0.8]]
b=>
 [[0.4 0.6 0.7]
 [0.8 0.9 1. ]]
Max-Min=>
 [[0.7 0.7]
 [0.7 0.8]]
Max-Product => :
[[0.49 0.7 ]
 [0.56 0.8 ]]




In [44]:

import numpy as np
def maxMin(a,b):
    z=[]
    for x1 in a:
        for y1 in b:
            z.append(max(np.minimum(x1, y1)))
    return np.array(z).reshape((a.shape[0], b.shape[0]))
def maxProduct(a,b):
    z=[]
    for x1 in a:
        for y1 in b:
            z.append(max(np.multiply(x1, y1)))
    return np.array(z).reshape((a.shape[0], b.shape[0]))
a=np.array([[0.2,0.3,0.5],[0.6,0.8,1]])
b=np.array([[0.1,0.4,0.7],[0.6,0.7,0.9]])
print('a=>\n',a)
print('b=>\n',b)
print('Max-Min=>\n',str(maxMin(a,b)))
print("Max-Product => :\n" + str(maxProduct(a, b)) + "\n\n")

a=>
 [[0.2 0.3 0.5]
 [0.6 0.8 1. ]]
b=>
 [[0.1 0.4 0.7]
 [0.6 0.7 0.9]]
Max-Min=>
 [[0.5 0.5]
 [0.7 0.9]]
Max-Product => :
[[0.35 0.45]
 [0.7  0.9 ]]


